### ISSUE TITLE
Power off Battery

### ISSUE THREAD

**Issue by sean-smith** [WKHarmon/led-sectional#13]
Is there an easy way to power off a battery? Was thinking it'd be great to enclose this completely in the frame with a rechargable battery. Unfortunately my knowledge of hardware is a bit limited, it seems like I could just find a cord that outputs 5V USB to the same size adapter, like [this](https://www.amazon.com/StarTech-com-USB2TYPEM-Barrel-Power-Cable/dp/B003MQO96U/ref=sr_1_4?crid=2727VXGFR3ALN&dchild=1&keywords=usb+to+5v+dc+cable&qid=1633379991&s=electronics&sprefix=usb+to+5v+%2Celectronics%2C216&sr=1-4)

What do you suggest?

**Comment by WKHarmon** [comment]
Yup, the Type M one from your link should work fine. I haven't done any proper benchmarking on how much power everything will draw--the microcontroller itself shouldn't draw much at all, but the LEDs will be nontrivial so I'm not sure how long it'll last. It seems worth a shot to grab a larger USB battery bank.

If you have fewer than about 50 LEDs and are using sane brightness levels, it should also be safe to power the entire thing off of the Micro USB port if you already have a USB-A to Micro USB cable lying around. (If you draw too much current on the Micro USB port it'll trip a fuse that will automatically reset itself after being unplugged for a few hours, so it shouldn't do any permanent damage.)

**Comment by sean-smith** [comment]
I tested this out with a normal sized external battery and it lasted only a few days. Wasn't worth the hassle of constantly charging the battery.
