### ISSUE TITLE
Coding

### ISSUE THREAD

**Issue by MatD13** [WKHarmon/led-sectional#15]
https://github.com/WKHarmon/led-sectional/blob/2923693a27e39514b676651f2cc5d0c5c9df14c0/led-sectional.ino#L9

Is there a way to have an airport that say for example is vfr, flash yellow vs staying yellow if the winds exceed the default value?

Also, if an airport stops reporting a METAR and goes blank on the sectional like I’ve noticed on occasion, is it possible to light it up a certain color?

**Comment by WKHarmon** [comment]
Hello! It is theoretically possible to have it flash, but it would require pretty significant refactoring of how the code works. If you end up modifying it to make that happen, submit a pull request and I'll add it as an option.

For using a different color for missing METARs, you'd just need to change the color on lines 309 and 502 to something else; however, note that this will also change any LEDs that are listed as NULL to your new color as well. (If they're hidden behind your map this probably doesn't matter, I guess.)
